/*
 * #%L
 * prolobjectlink-db
 * %%
 * Copyright (C) 2012 - 2018 Logicware Project
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

package org.logicware.pdb.ql;

//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 21 14:34:21 VET 2009
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 20;
  public static final int INPUT = 2;
  public static final int ELSE = 9;
  public static final int PLUS = 19;
  public static final int THEN = 8;
  public static final int END = 5;
  public static final int FI = 10;
  public static final int ERROR = 11;
  public static final int IF = 7;
  public static final int ID = 23;
  public static final int LE = 16;
  public static final int COMMA = 12;
  public static final int NUMBER = 24;
  public static final int EOF = 0;
  public static final int DIV = 21;
  public static final int MINUS = 18;
  public static final int ARGUMENTS = 6;
  public static final int error = 1;
  public static final int EQ = 15;
  public static final int FUNCTIONS = 3;
  public static final int LEQ = 17;
  public static final int RPAR = 14;
  public static final int OUTPUT = 4;
  public static final int LPAR = 13;
  public static final int UMINUS = 22;
}

